
# folder path of dataset, which includes 2 subfolders: cloudy_image/ and ground_truth/
datasets_dir: RICE #Dataset name, the path of the dataset need to change in the dataload

out_dir: /xxxxx   #your output dir path

cuda: True
gpu_ids: [1]

batchsize: 2
validation_batchsize: 1
epoch: 200
n_data: 433
width: 256
height: 256
threads: 4

lr: 0.0001
beta1: 0.5
lamb: 100
minimax: 1

gen_init: 
dis_init: 
in_ch: 3
out_ch: 3

manualSeed: 0
snapshot_interval: 1

model: mn
print_every: 50